# -*- coding: utf-8 -*-
# Nasdaq-100: (ticker, peso%, sector, sub-nicho). Pesos slickcharts ~04/08/2026.
COMPONENTS = [
("NVDA",12.21,"Technology","Semiconductors"),("AAPL",10.81,"Technology","Consumer Electronics"),
("MSFT",8.83,"Technology","Software - Infrastructure"),("AMZN",7.19,"Consumer Cyclical","Internet Retail"),
("GOOGL",5.69,"Communication Services","Internet Content & Information"),("GOOG",5.32,"Communication Services","Internet Content & Information"),
("AVGO",4.75,"Technology","Semiconductors"),("SPCX",3.84,"Industrials","Aerospace & Defense"),
("META",3.56,"Communication Services","Internet Content & Information"),("TSLA",3.08,"Consumer Cyclical","Auto Manufacturers"),
("MU",2.43,"Technology","Semiconductors"),("WMT",2.10,"Consumer Defensive","Discount Stores"),
("AMD",2.05,"Technology","Semiconductors"),("ASML",1.56,"Technology","Semiconductor Equip. & Materials"),
("INTC",1.21,"Technology","Semiconductors"),("CSCO",1.14,"Technology","Communication Equipment"),
("AMAT",1.04,"Technology","Semiconductor Equip. & Materials"),("COST",1.00,"Consumer Defensive","Discount Stores"),
("LRCX",0.94,"Technology","Semiconductor Equip. & Materials"),("PLTR",0.93,"Technology","Software - Infrastructure"),
("NFLX",0.73,"Communication Services","Entertainment"),("ARM",0.71,"Technology","Semiconductors"),
("PANW",0.70,"Technology","Software - Infrastructure"),("TXN",0.62,"Technology","Semiconductors"),
("KLAC",0.61,"Technology","Semiconductor Equip. & Materials"),("LIN",0.54,"Basic Materials","Specialty Chemicals"),
("CRWD",0.51,"Technology","Software - Infrastructure"),("SNDK",0.51,"Technology","Computer Hardware"),
("AMGN",0.50,"Healthcare","Drug Manufacturers - General"),("MRVL",0.47,"Technology","Semiconductors"),
("STX",0.47,"Technology","Computer Hardware"),("WDC",0.46,"Technology","Computer Hardware"),
("PEP",0.45,"Consumer Defensive","Beverages - Non-Alcoholic"),("TMUS",0.45,"Communication Services","Telecom Services"),
("ADI",0.44,"Technology","Semiconductors"),("QCOM",0.41,"Technology","Semiconductors"),
("GILD",0.39,"Healthcare","Drug Manufacturers - General"),("SHOP",0.38,"Technology","Software - Application"),
("BKNG",0.35,"Consumer Cyclical","Travel Services"),("APP",0.33,"Communication Services","Advertising Agencies"),
("ISRG",0.32,"Healthcare","Medical Instruments & Supplies"),("PDD",0.31,"Consumer Cyclical","Internet Retail"),
("FTNT",0.29,"Technology","Software - Infrastructure"),("VRTX",0.29,"Healthcare","Biotechnology"),
("SBUX",0.29,"Consumer Cyclical","Restaurants"),("ADP",0.26,"Technology","Software - Application"),
("DDOG",0.24,"Technology","Software - Application"),("ADBE",0.24,"Technology","Software - Application"),
("CEG",0.23,"Utilities","Utilities - Renewable"),("MELI",0.23,"Consumer Cyclical","Internet Retail"),
("CDNS",0.23,"Technology","Software - Application"),("CSX",0.22,"Industrials","Railroads"),
("MNST",0.22,"Consumer Defensive","Beverages - Non-Alcoholic"),("MAR",0.22,"Consumer Cyclical","Travel Services"),
("ABNB",0.21,"Consumer Cyclical","Travel Services"),("INTU",0.21,"Technology","Software - Application"),
("CMCSA",0.21,"Communication Services","Telecom Services"),("DASH",0.21,"Consumer Cyclical","Internet Retail"),
("CTAS",0.20,"Industrials","Specialty Business Services"),("ROST",0.19,"Consumer Cyclical","Apparel Retail"),
("HON",0.19,"Industrials","Conglomerates"),("MDLZ",0.19,"Consumer Defensive","Confectioners"),
("REGN",0.19,"Healthcare","Biotechnology"),("SNPS",0.18,"Technology","Software - Infrastructure"),
("ORLY",0.18,"Consumer Cyclical","Specialty Retail"),("PCAR",0.17,"Industrials","Farm & Heavy Constr. Machinery"),
("AEP",0.17,"Utilities","Utilities - Regulated Electric"),("HONA",0.16,"Industrials","Aerospace & Defense"),
("LITE",0.16,"Technology","Communication Equipment"),("MPWR",0.16,"Technology","Semiconductors"),
("WBD",0.16,"Communication Services","Entertainment"),("TER",0.15,"Technology","Semiconductor Equip. & Materials"),
("ALAB",0.15,"Technology","Semiconductors"),("BKR",0.15,"Energy","Oil & Gas Equip. & Services"),
("NXPI",0.14,"Technology","Semiconductors"),("NBIS",0.14,"Technology","Software - Infrastructure"),
("FAST",0.13,"Industrials","Industrial Distribution"),("FANG",0.13,"Energy","Oil & Gas E&P"),
("EA",0.13,"Communication Services","Electronic Gaming & Multimedia"),("CRWV",0.12,"Technology","Software - Infrastructure"),
("PYPL",0.12,"Financial Services","Credit Services"),("ADSK",0.12,"Technology","Software - Application"),
("XEL",0.12,"Utilities","Utilities - Regulated Electric"),("AXON",0.12,"Industrials","Aerospace & Defense"),
("FER",0.11,"Industrials","Engineering & Construction"),("IDXX",0.11,"Healthcare","Diagnostics & Research"),
("EXC",0.11,"Utilities","Utilities - Regulated Electric"),("RKLB",0.11,"Industrials","Aerospace & Defense"),
("CCEP",0.11,"Consumer Defensive","Beverages - Non-Alcoholic"),("TRI",0.11,"Industrials","Specialty Business Services"),
("ODFL",0.11,"Industrials","Trucking"),("TTWO",0.11,"Communication Services","Electronic Gaming & Multimedia"),
("MCHP",0.10,"Technology","Semiconductors"),("KDP",0.10,"Consumer Defensive","Beverages - Non-Alcoholic"),
("PAYX",0.10,"Technology","Software - Application"),("WDAY",0.10,"Technology","Software - Application"),
("ROP",0.09,"Industrials","Specialty Industrial Machinery"),("MSTR",0.08,"Technology","Software - Application"),
("DXCM",0.08,"Healthcare","Medical Devices"),("GEHC",0.08,"Healthcare","Diagnostics & Research"),
("KHC",0.08,"Consumer Defensive","Packaged Foods"),("ALNY",0.07,"Healthcare","Biotechnology"),
("CPRT",0.06,"Industrials","Specialty Business Services"),
]
# Tickers no cotizados en yfinance (se omiten del cálculo de performance diaria)
SKIP_PRICE = {"SPCX","HONA"}
